gateway023

diff --git a/work/qtz/gateway/Dockerfile b/work/qtz/gateway/Dockerfile
--- a/work/qtz/gateway/Dockerfile
+++ b/work/qtz/gateway/Dockerfile
@@ -5,7 +5,7 @@ ENV BASE_DIR="/data" \
     NGINX_VERSION="nginx-1.7.9" \
     PHP_VERSION="php-5.6.3"
 ENV SOFT_PATH="${BASE_DIR}/soft" \
-    APP_PATH="${BASE_DIR}/apps" \
+    NGINX_PATH="${BASE_DIR}/nginx" \
     WEB_PATH="${BASE_DIR}/www" \
     NGINX_PACKAGE="${NGINX_VERSION}.tar.gz" \
     PHP_PACKAGE="${PHP_VERSION}.tar.gz" \
@@ -20,9 +20,9 @@ ENV SOFT_PATH="${BASE_DIR}/soft" \
     THRIFT_VERSION="thrift-0.9.3.tar.gz" \
     THRIFT_PATH="${BASE_DIR}/thrift"
 
-RUN mkdir ${BASE_DIR} && \
-    mkdir -p ${APP_PATH}/nginx && \
-    cd ${BASE_DIR} && \
+RUN mkdir -p ${NGINX_PATH} && \
+    mkdir -p ${SOFT_PATH} && \
+    #
     groupadd nginx && \
     useradd -g nginx nginx -s /sbin/nologinmake
 RUN yum install pcre pcre-devel -y && \
@@ -36,7 +36,7 @@ RUN echo $HOSTIP $HOSTNAME>>/etc/hosts; \
     tar zxvf ${NGINX_PACKAGE} && \
     cd ${NGINX_VERSION} && \ 
     ./configure \
-    --prefix=${APP_PATH}/nginx \
+    --prefix=${NGINX_PATH} \
     --with-cc-opt=-O3 \
     --user=nginx \
     --group=nginx \
@@ -45,11 +45,8 @@ RUN echo $HOSTIP $HOSTNAME>>/etc/hosts; \
     --with-http_ssl_module \
     --with-http_realip_module && \
     make && make install && \
-    mv ${APP_PATH}/nginx/conf/nginx.conf ${APP_PATH}/nginx/conf/nginx.conf.default && \
-    mkdir -p ${WEB_PATH} && \
-    chown -R nginx:nginx ${WEB_PATH} && \
     rm -rf ${SOFT_PATH}/*
-COPY nginx.conf ${APP_PATH}/nginx/conf/
+# COPY nginx.conf ${APP_PATH}/nginx/conf/
 # Install PHP
 WORKDIR ${SOFT_PATH}
 RUN yum install libxml2-devel bzip2-devel libcurl-devel libjpeg-devel libpng-devel freetype-devel unzip -y && \
@@ -128,33 +125,33 @@ RUN echo ${HOSTIP} ${HOSTNAME}>>/etc/hosts && \
     make && make install
 
 # 安装memcached
-WORKDIR ${SOFT_PATH}
-RUN echo $HOSTIP $HOSTNAME>>/etc/hosts && \
-    wget -P ${SOFT_PATH} http://${HOSTNAME}/memcached-1.4.33.tar.gz && \
-    wait && \
-    tar xzf memcached-1.4.33.tar.gz && \
-    cd memcached-1.4.33 && \
-    pwd && ls && \
+#WORKDIR ${SOFT_PATH}
+#RUN echo $HOSTIP $HOSTNAME>>/etc/hosts && \
+#    wget -P ${SOFT_PATH} http://${HOSTNAME}/memcached-1.4.33.tar.gz && \
+#    wait && \
+#    tar xzf memcached-1.4.33.tar.gz && \
+#    cd memcached-1.4.33 && \
+#    pwd && ls && \
 #    ${BASE_DIR}/php/bin/phpize ./ && \
-    ./configure --prefix=${MEMCACHED_PATH} --with-libevent=${LIBEVENT_PATH} && \
-    make && make install && \
-    sed -i '865i\extension=memcache.so' /etc/php.ini && \
-    ${MEMCACHED_PATH}/bin/memcached -d -m 1024 -u root -p 11211 -c 256 -P /tmp/memcached.pid && \
-    echo "${MEMCACHED_PATH}/bin/memcached -d -m 1024 -u root -p 11211 -c 2048 -P /tmp/memcached.pid" >> /etc/rc.local && \
-    rm -rf ${SOFT_PATH}/*
+#    ./configure --prefix=${MEMCACHED_PATH} --with-libevent=${LIBEVENT_PATH} && \
+#    make && make install && \
+#    sed -i '865i\extension=memcache.so' /etc/php.ini && \
+#    ${MEMCACHED_PATH}/bin/memcached -d -m 1024 -u root -p 11211 -c 256 -P /tmp/memcached.pid && \
+#    echo "${MEMCACHED_PATH}/bin/memcached -d -m 1024 -u root -p 11211 -c 2048 -P /tmp/memcached.pid" >> /etc/rc.local && \
+#    rm -rf ${SOFT_PATH}/*
 
 # 安装memcache 
-WORKDIR ${SOFT_PATH}
-RUN echo $HOSTIP $HOSTNAME>>/etc/hosts && \
-    wget -P ${SOFT_PATH} http://${HOSTNAME}/memcache-2.2.7.tgz && \
-    wait && \
-    tar xzf memcache-2.2.7.tgz && \
-    cd memcache-2.2.7 && \
-    ${PHP_PATH}/bin/phpize && \
-    ./configure --enable-memcache --with-php-config=${PHP_PATH}/bin/php-config --with-zlib-dir && \
-    make && make install && \
-    sed -i '865i\extension=memcache.so' /etc/php.ini && \
-    rm -rf ${SOFT_PATH}/*
+#WORKDIR ${SOFT_PATH}
+#RUN echo $HOSTIP $HOSTNAME>>/etc/hosts && \
+#    wget -P ${SOFT_PATH} http://${HOSTNAME}/memcache-2.2.7.tgz && \
+#    wait && \
+#    tar xzf memcache-2.2.7.tgz && \
+#    cd memcache-2.2.7 && \
+#    ${PHP_PATH}/bin/phpize && \
+#    ./configure --enable-memcache --with-php-config=${PHP_PATH}/bin/php-config --with-zlib-dir && \
+#    make && make install && \
+#    sed -i '865i\extension=memcache.so' /etc/php.ini && \
+#    rm -rf ${SOFT_PATH}/*
 
 # 安装librdkafka
 WORKDIR ${SOFT_PATH}
@@ -210,14 +207,60 @@ RUN echo $HOSTIP $HOSTNAME>>/etc/hosts && \
     cd ${source_dir} && \
     ./configure --prefix=${THRIFT_PATH} --with-php=yes --with-cpp=no --with-lua=no && \
     make && make install && cd .. && \
-    echo "export PATH=${thriftInstallPath}/bin:\$PATH" >> /etc/profile.d/thrift.sh && \
+    echo "export PATH=${THRIFT_PATH}/bin:\$PATH" >> /etc/profile.d/thrift.sh && \
     source /etc/profile.d/thrift.sh && \
     rm -rf ${SOFT_PATH}/*
 
-COPY conf/opt-test.json /etc/consul.d/opt-test.json
-COPY start.sh ${BASE_DIR}
+
+# 配置和启动
+COPY conf/nginxd /etc/init.d/nginxd
+WORKDIR ${BASE_DIR}
+RUN echo "配置..." && \
+    echo $HOSTIP $HOSTNAME>>/etc/hosts && \
+    chmod 755 /etc/init.d/nginxd && \
+    mkdir ${NGINX_PATH}/conf/vhost && \
+    cd ${NGINX_PATH}/conf && \
+    wget -O nginx.conf http://${HOSTNAME}/NginxConf/nginx.conf && \
+    wget -P ${NGINX_PATH}/conf/vhost http://${HOSTNAME}/NginxConf/default.conf && \
+    wget -P ${NGINX_PATH}/conf/vhost http://${HOSTNAME}/NginxConf/demo.vikduo.com.conf && \
+    /etc/init.d/nginxd start && \
+    test "$(netstat -ntlp | grep nginx)" == "" && echo "Start Nginx failed" || echo "Start Nginx OK" && \
+    echo "export PATH=\$PATH:${NGINX_PATH}/sbin" > /etc/profile.d/nginx.sh && \
+    . /etc/profile.d/nginx.sh && \    
+    mkdir -p ${WEB_PATH} && \
+    chown nginx:nginx ${WEB_PATH}
+
+ADD _code_ ${BASE_DIR}/www
 ADD www ${BASE_DIR}/www
-RUN chown nginx:nginx ${BASE_DIR}/www && \
-    chmod +x ${BASE_DIR}/start.sh
+ADD vhost ${NGINX_PATH}/conf/vhost
+COPY conf/opt-test.json /etc/consul.d/opt-test.json
+COPY start.sh /start.sh
+# 网关部署 
+RUN cd ${WEB_PATH} && \
+    ln -s gateway-app-salesman appdt.testopt.snsshop.net && \
+    ln -s gateway-app-merchant appmc.testopt.snsshop.net && \
+    ln -s gateway-boss boss.testopt.snsshop.net && \
+    ln -s gateway-h5-rest-shop merc.testmopt.snsshop.net && \
+    ln -s gateway-h5-pay pay.testmopt.snsshop.net && \
+    ln -s gateway-qrcode qr.testmopt.snsshop.net && \
+    ln -s frontend-h5-rest-shop \*.testmopt.snsshop.net && \
+    ln -s gateway-h5-ucenter user.testmopt.snsshop.net && \
+    # init
+    cd gateway-qrcode && \
+    ${PHP_PATH}/bin/php init --env=Test --overwrite=All && \
+    mkdir ./runtime/debug && mkdir ./runtime/logs && \
+    chown -R nginx:nginx ./runtime && \
+    # 生成thrift code
+    ${THRIFT_PATH}/bin/thrift -out . --gen php:server thriftFiles/thriftServices.demo.thrift && \
+    ${THRIFT_PATH}/bin/thrift -out . --gen php:server thriftFiles/thriftServices.qrcode.thrift && \
+    ${THRIFT_PATH}/bin/thrift -out . --gen php:server thriftFiles/thriftServices.shared.thrift && \
+    # 启动服务
+    ${PHP_PATH}/bin/php start.php start -d && \
+    ${PHP_PATH}/bin/php start.php status && \
+    # Start 
+    chmod +x /start.sh && \
+    cd /${BASE_DIR}
+ 
+
 # END
-CMD ${BASE_DIR}/start.sh
+CMD /start.sh
